### ISSUE TITLE
Python 3.4

### ISSUE THREAD

**Issue by codeworkx** [Mechazawa/PyVbus#1]
line 290, in _lrecv
    s += c
TypeError: Can't convert 'bytes' object to str implicitly

Resolution:

```
def _lrecv(self):
    c, s = '', ''
    while c != b'\n':
        c = self._sock.recv(1)
        if c == '':
            break
        s += c.decode("utf-8") 
    s = s.strip('\r\n')
    if self.debugmode & DEBUG_COMMAND:
        print("< " + s)
    return s

def _lsend(self, s):
    if self.debugmode & DEBUG_COMMAND:
        print("> " + s)
        msg = s + "\r\n"
    self._sock.send(msg.encode("utf-8"))
```

**Comment by Mechazawa** [comment]
Thanks! I applied the bugfix.

**Comment by codeworkx** [comment]
There are a lot more things to do for python3.
i'll send a pull request when i'm done.

is it ok to loose python2 compat?

**Comment by Mechazawa** [comment]
I think python2 compatibility is not as important anymore as it was a year ago. So go ahead.

**Comment by codeworkx** [comment]
Ok, had success with the sonnenkraft sksc2 he.

Here's the result:
https://github.com/codeworkx/PyVbus/commit/ca79879ebe6267c7d3002b69ff4d38e39780dd9f

Can you test it with your own payload map, frame count and payloadsize?

**Comment by Mechazawa** [comment]
Looks good, the diff looks like it's almost an entire rewrite. I'll test it out tomorrow.
